### PR TITLE
Update - cloud_firestore

### PR DESCRIPTION
**Pull request by jimmy-to-goldenowl**
## TODO:
- [x] Upgrading-pre-1.12-Android-projects  => https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
- [x] Update cloud_firestore 
- [x] compileSdkVersion 31

### CODE REVIEW

**Comment by jimmy-to-goldenowl** [comment]
can use dependency_overrides

dependency_overrides:
  cloud_firestore: 4.6.0

**Comment by jimmy-to-goldenowl** [comment]
can use dependency_overrides

dependency_overrides:
  cloud_firestore: 4.6.0

**Comment by IncognitoGK9** [comment]
I see the dependency on cloud_firestore: 4.6.0 was committed, is it like @DarshanGowda0 has not approved yet?

**Comment by kosukesaigusa** [comment]
Sorry for the comments from outside!

In order to for being always compatible with latest dependency, the package below, heavily inspired by geoflutterfire/geoflutterfire2, is released a few month ago with full respect!

https://pub.dev/packages/geoflutterfire_plus

https://github.com/KosukeSaigusa/geoflutterfire_plus

Almost all the existing features are available. But whole codes are redesigned and refactored for future extensibility and easy maintenance. So features and unit tests are also added (e.g. fetching geo locations once as `Future` method).

Some of the definitions and names of classes, methods, and variables are different, so once you may need to refactor you code🙏

If you are interested, please check [geoflutterfire_plus](https://pub.dev/packages/geoflutterfire_plus)!

I'm trying to constantly maintain the package and its dependency, so course, feature/pull requests are always welcome🙌

**Comment by IncognitoGK9** [comment]
I will be looking at it and give you feedback tomorrow.
Thank You.

With regards,

Handson

Ombiro
***@***.***
+254721966366

*P* Before you print think about the ENVIRONMENT

**Pull request closed without merging**
