### PR TITLE
cloud_firestore dependency bump

### PR DESCRIPTION
**Pull request by prascuna**
Hi there,
I'm not quite sure what's the best way to contribute and how to test it, but I'm happy to help if I'm guided a bit.
I hope that the CI will kick in after raising this PR and run the tests for me :D 

Solves #133

### CODE REVIEW

**Comment by prascuna** [comment]
nope...no tests run by the CI. Any advice?

**Comment by manafire** [comment]
I don't think there are any tests to run.  I cloned your fork locally and am able to run it successfully without any problems.  Thanks!

**Review by iamgenes — APPROVED** [review]

**Comment by prascuna** [comment]
Thanks for the approval @iamgenes . There are already other PRs opened with the same changes... any chance you or @DarshanGowda0 can merge one of them?

**Comment by iamgenes** [comment]
Looks like @DarshanGowda0  is currently taking a break I approved the PR but I do not have access to merge PRs, I also sent an email to @DarshanGowda0 to approve the PRs.

**Comment by vishnuagbly** [comment]
Currently, there are more than 4 forked versions of this library, We are currently thinking to create a single temporary forked or copied version of the repo to work on further development. Anyone who wants to contribute is welcome to join our [Discord Group](https://discord.gg/PWGGgXMv) made for discussion.

**Comment by awaik** [comment]
Thank you for this pull request. 
Because of our delay with reaction, there were other updates and we made it all together with another branch. 
You are welcome to make new PRs, we will try to react quickly.

**Pull request closed without merging**
