### PR TITLE
Update flutter_lints to 2.x

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by cedvdb** [comment]
were there 0 lint issues ? Usually just changing the number is not enough, lint issues will appear in the project

**Comment by ghost** [comment]
I did not run the update against the example code or the library. Does the update create new lint warnings?

**Comment by cedvdb** [comment]
I don't know, I'm not the one submitting the PR. I'm asking if you checked ? If you use vs code it automatically shows up in the "problems" tab once you update the lint dep

**Comment by cedvdb** [comment]
@DarshanGowda0

**Comment by jacksoncurrie** [comment]
Wouldn't it be a better idea to move the `flutter_lints` package to `dev_dependencies:` as it's only required for development? This would fix conflicts for every version going forward for anyone who uses the package.

See #190 for changes.

**Comment by ghost** [comment]
Agree w/ #190

**Pull request closed without merging**
