### PR TITLE
Null Safe version

### PR DESCRIPTION
**Pull request by jonbhanson**
Adds null safety.  I updated the example based on the latest version of the Flutter example app.  I also added instructions in the example for setting up the example app with Firebase and Maps API keys, etc.

This should be reviewed as I worked quickly to get it out.

Although I added this as a pull request, I suggest that instead this should be `git fetch`ed to create a new 3.x branch in this project.  The 2.x will probably continue to require maintenance for a while until the community has moved to Flutter 2.0, so it would be helpful to keep separate 2.x and 3.x branches.

### CODE REVIEW

**Comment by awaik** [comment]
Hey @jonbhanson,
thank you!
To be clear - you suggest make `git fetch` and after that, close this pull request. Correct?
I will create `3x_null_safety` branch.

**Comment by jonbhanson** [comment]
Yes👍🏻

**Comment by awaik** [comment]
Done.
Tomorrow and Monday will review and after that upload to the pub.dev
Already had a quick look at changes - great job @jonbhanson 👍🏻👍🏻

**Comment by zeusbaba** [comment]
good job @jonbhanson  
kindly note that https://github.com/DarshanGowda0/GeoFlutterFire/pull/146#issuecomment-792032163

**Review by zeusbaba — APPROVED** [review]
plz kindly resolve merge-conflicts before any merge to `master` branch

**Comment by awaik** [comment]
Hey @zeusbaba 
As @jonbhanson asked we should close this PR without merging.
It is already online on the branch https://github.com/DarshanGowda0/GeoFlutterFire/tree/3x_null_safety
Please, read the first message in this thread.

**Pull request closed without merging**
