### PR TITLE
upgrade dependencies

### PR DESCRIPTION
**Pull request by zeusbaba**
upgrade dependencies, and update example project

### CODE REVIEW

**Comment by sammy44nts** [comment]
Closes #133

Closes #137

**Comment by zeusbaba** [comment]
while waiting for PR to be merged, you can use the up2date version directly from my fork  
```
geoflutterfire:
    git: git://github.com/beerstorm-net/GeoFlutterFire.git
```

**Comment by LucaDillenburg** [comment]
Please, merge as soon as possible...

**Comment by zeusbaba** [comment]
@DarshanGowda0 it seems that this repo is not actively maintained anymore. I can volunteer to help by becoming a maintainer. Let me know what you think?

**Comment by vishnuagbly** [comment]
@zeusbaba why not upload your own forked package, it could help a lot of people

**Comment by zeusbaba** [comment]
I notice the popular opinion. 
I totally agree that this package requires more active ownership.  
I gladly will take on this task and publish a refreshed version of this package soon.

**Comment by jonbhanson** [comment]
@zeusbaba I have a null safe version ready. I will push the update to my fork right away so others can test it.

**Comment by jonbhanson** [comment]
My null-safe fork can be found [here](https://github.com/jonbhanson/GeoFlutterFire).  It is a work in progress, so please let me know about any problem you run into.

geoflutterfire:
    git: git://github.com/jonbhanson/GeoFlutterFire.git

**Comment by vishnuagbly** [comment]
Currently, there are more than 4 forked versions of this library, We are currently thinking to create a single temporary forked or copied version of the repo to work on further development. Anyone who wants to contribute is welcome to join our [Discord Group](https://discord.gg/PWGGgXMv) made for discussion.

**Comment by jonbhanson** [comment]
I made my comments above quickly because I didn't want @zeusbaba to waste work on null safety that I had already done.  If I had taken a little more time for thought, I should have offered to make a PR with my changes to @zeusbaba's fork.  I'm happy to close my fork and work together with anyone on a single fork for the community. 👍🏻

**Comment by DarshanGowda0** [comment]
Sorry for the delayed response guys! I’ve been off the platform for personal reasons.
I’ve added @zeusbaba as a maintainer now!

**Comment by Vitor-Bukovitz** [comment]
@zeusbaba  can you merge this PR? We really need this update

**Comment by awaik** [comment]
Thank you for this pull request. We've updated all together with another branch. You are welcome for future updates, we will try to react quickly.

**Comment by zeusbaba** [comment]
well, you've closed this PR without merge, but...
the other branch, #144 ?, is still using `cloud_firestore: ^0.16.0`  which is old...  
This PR was intending to upgrade dependencies and make it working with Flutter2 as well.

**Comment by zeusbaba** [comment]
@DarshanGowda0 thnx for adding me as a maintainer.

**Comment by zeusbaba** [comment]
nevertheless, I have just created a new PR #146 which requires review.  

p.s. I've also started _a sister-project_ [GeoFlutterFire2](https://pub.dev/packages/geoflutterfire2) on the sideline, for extending with more customizations.  Open for all.

**Comment by awaik** [comment]
@zeusbaba I think we should go with this PR https://github.com/DarshanGowda0/GeoFlutterFire/pull/147
After that, we will have 2 branches and will have the possibility to make PR's for different versions - with null safety and without.

**Pull request closed without merging**
